apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: master-2020-05-20-8e0ac0f
  name: conprof
  namespace: conprof
spec:
  clusterIP: None
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
