apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: master-2020-05-20-8e0ac0f
  name: conprof
  namespace: conprof
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
  serviceName: conprof
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: conprof
        app.kubernetes.io/name: conprof
        app.kubernetes.io/version: master-2020-05-20-8e0ac0f
    spec:
      containers:
      - args:
        - all
        - --storage.tsdb.path=/conprof
        - --config.file=/etc/conprof/conprof.yaml
        image: quay.io/conprof/conprof:master-2020-05-20-8e0ac0f
        name: conprof
        ports:
        - containerPort: 10902
          name: http
        volumeMounts:
        - mountPath: /conprof
          name: storage
          readOnly: false
        - mountPath: /etc/conprof
          name: config
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: conprof
      volumes:
      - emptyDir: {}
        name: storage
      - name: config
        secret:
          secretName: conprof-config
